#include "TROOT.h"
// #include <TGXW.h>    - for version 2.22.10
#include <TApplication.h>
//#include <TRootApplication.h>
#include <TVirtualX.h>

#include <TGListBox.h>
#include <TGClient.h>
#include <TGFrame.h>
#include <TGIcon.h>
#include <TGLabel.h>
#include <TGButton.h>
#include <TGTextEntry.h>
#include <TGMsgBox.h>
#include <TGMenu.h>
#include <TGCanvas.h>
#include <TGComboBox.h>
#include <TGTab.h>
#include <TGSlider.h>
#include <TGDoubleSlider.h>
#include <TGFileDialog.h>
#include <TRootEmbeddedCanvas.h>
#include <TH1.h>
#include <TH2.h>
#include <TProfile.h>
#include <TRandom.h>
#include <TSystem.h>
#include <TEnv.h>
#include "TMath.h"
//#include "TTreeViewer.h"

#include "TArc.h"
#include "TStyle.h"
#include "TCanvas.h"
#include "TPad.h"
#include "TColor.h"
#include "TPaveLabel.h"
//#include "TPaveStats.h"
//#include "TAxis.h"
#include "TMarker.h"
#include "TPolyMarker3D.h"
#include "TPaveText.h"
#include <TGMsgBox.h>
#include <TGLabel.h>
#include <TGFileDialog.h>
//#include <TGFSContainer.h>
#include <TSystem.h>
#include <TObject.h>
//#include <TGObject.h>
#include <TObjectTable.h>
//#include <TCollection.h>
#include <TView.h>
#include <THelix.h>
#include <TGraph.h>
#include <TEnv.h>
#include "TStopwatch.h"
#include "TPolyMarker.h"
#include "TF1.h"
#include "TNamed.h"
#include "TText.h"
